name: ucl_data_eng
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - pandas
  - numpy
  - pyarrow
  - duckdb
  - pymongo
  - pyspark
  - matplotlib
  - pip:
      - python-dotenv
